/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcStarter {
    /**
    * A image prop
    */
    'image': string;
    /**
    * A text prop
    */
    'text': string;
  }
  interface WcUiInput {
    'value': string;
  }
}

declare global {


  interface HTMLWcStarterElement extends Components.WcStarter, HTMLStencilElement {}
  var HTMLWcStarterElement: {
    prototype: HTMLWcStarterElement;
    new (): HTMLWcStarterElement;
  };

  interface HTMLWcUiInputElement extends Components.WcUiInput, HTMLStencilElement {}
  var HTMLWcUiInputElement: {
    prototype: HTMLWcUiInputElement;
    new (): HTMLWcUiInputElement;
  };
  interface HTMLElementTagNameMap {
    'wc-starter': HTMLWcStarterElement;
    'wc-ui-input': HTMLWcUiInputElement;
  }
}

declare namespace LocalJSX {
  interface WcStarter {
    /**
    * A image prop
    */
    'image'?: string;
    /**
    * A text prop
    */
    'text'?: string;
  }
  interface WcUiInput {
    'onEventChange'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }

  interface IntrinsicElements {
    'wc-starter': WcStarter;
    'wc-ui-input': WcUiInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wc-starter': LocalJSX.WcStarter & JSXBase.HTMLAttributes<HTMLWcStarterElement>;
      'wc-ui-input': LocalJSX.WcUiInput & JSXBase.HTMLAttributes<HTMLWcUiInputElement>;
    }
  }
}


