/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcStarter {
    /**
    * A image prop
    */
    'image': string;
    /**
    * A text prop
    */
    'text': string;
  }
}

declare global {


  interface HTMLWcStarterElement extends Components.WcStarter, HTMLStencilElement {}
  var HTMLWcStarterElement: {
    prototype: HTMLWcStarterElement;
    new (): HTMLWcStarterElement;
  };
  interface HTMLElementTagNameMap {
    'wc-starter': HTMLWcStarterElement;
  }
}

declare namespace LocalJSX {
  interface WcStarter {
    /**
    * A image prop
    */
    'image'?: string;
    /**
    * A text prop
    */
    'text'?: string;
  }

  interface IntrinsicElements {
    'wc-starter': WcStarter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wc-starter': LocalJSX.WcStarter & JSXBase.HTMLAttributes<HTMLWcStarterElement>;
    }
  }
}


